"""Configurable orchestration for one ATP analysis run."""

from dataclasses import dataclass

import polars as pl
from matplotlib.figure import Figure

from src.services.clustering import (
    cluster_kmeans,
    detect_outliers_dbscan_per_terminal,
    filter_valid_events,
)
from src.services.comparison import compare_anomaly_methods
from src.services.config import AnalysisConfig
from src.services.preprocessing import load_directory
from src.services.statistics import (
    GaussianFitResult,
    fit_gaussian,
    summarize_statistics,
)
from src.services.validation import ValidationResult, validate_observations
from src.services.visualization import plot_combined, plot_exceedance_curve


@dataclass(frozen=True, slots=True)
class PipelineFigures:
    """Figures generated by an analysis run."""

    combined: Figure
    exceedance: Figure


@dataclass(frozen=True, slots=True)
class PipelineResult:
    """In-memory evidence produced by an analysis run."""

    raw_observations: pl.DataFrame
    validation: ValidationResult
    annotated_observations: pl.DataFrame
    summary: pl.DataFrame
    figures: PipelineFigures


def run_pipeline(config: AnalysisConfig) -> PipelineResult:
    """Run loading, validation, analysis, comparison, and plotting.

    Returns:
        Raw and annotated observations, validation evidence, statistical
        summaries, and generated figures.

    Raises:
        ValueError: If the selected observations cannot be analyzed or the
            K-Means cluster count exceeds the analyzed row count.
    """
    raw_observations = load_directory(
        directory=config.input_path,
        base_voltage=config.base_voltage,
        terminal_names=set(config.terminals),
        encoding=config.encoding,
    )
    validation = validate_observations(
        raw_observations,
        terminals=config.terminals,
        phases=(config.phase_policy,),
    )
    if not validation.is_valid:
        message = (
            "The selected observations cannot be analyzed: "
            f"{validation.status.value}."
        )
        raise ValueError(message)

    analyzed = validation.cleaned
    if config.kmeans.n_clusters > analyzed.height:
        message = (
            "K-Means n_clusters must not exceed the analyzed row count "
            f"({analyzed.height})."
        )
        raise ValueError(message)

    dbscan_labelled = detect_outliers_dbscan_per_terminal(
        analyzed,
        eps=config.dbscan.eps,
        min_samples=config.dbscan.min_samples,
    )
    clustered = cluster_kmeans(
        dbscan_labelled,
        n_clusters=config.kmeans.n_clusters,
        random_state=config.kmeans.random_state,
    )
    valid_events = filter_valid_events(clustered)
    summary = summarize_statistics(
        valid_events,
        threshold=config.threshold,
    )
    annotated = _add_sigma_flags(clustered, summary)
    compared = compare_anomaly_methods(annotated)
    fits = _build_plot_fits(valid_events, summary)

    combined, _ = plot_combined(
        compared,
        cluster_col="dbscan_cluster",
    )
    exceedance, _ = plot_exceedance_curve(
        df=compared,
        fits=fits,
        cluster_col="dbscan_cluster",
    )

    return PipelineResult(
        raw_observations=raw_observations,
        validation=validation,
        annotated_observations=compared,
        summary=summary,
        figures=PipelineFigures(
            combined=combined,
            exceedance=exceedance,
        ),
    )


def _add_sigma_flags(
    observations: pl.DataFrame,
    summary: pl.DataFrame,
) -> pl.DataFrame:
    thresholds = summary.select(
        "terminal",
        "phase",
        "sigma_3_threshold",
    )
    return (
        observations
        .join(
            thresholds,
            on=["terminal", "phase"],
            how="left",
            maintain_order="left",
        )
        .with_columns(
            (
                pl.col("sigma_3_threshold").is_not_null()
                & (pl.col("value_pu") > pl.col("sigma_3_threshold"))
            ).alias("sigma_flag")
        )
        .drop("sigma_3_threshold")
    )


def _build_plot_fits(
    observations: pl.DataFrame,
    summary: pl.DataFrame,
) -> dict[str, GaussianFitResult]:
    valid_terminals = set(
        summary.filter(pl.col("validation_status") == "valid")["terminal"]
    )
    fits: dict[str, GaussianFitResult] = {}
    for terminal in valid_terminals:
        subset = observations.filter(pl.col("terminal") == terminal)
        fits[terminal] = fit_gaussian(subset)
    return fits
