"""Configurable orchestration for one ATP analysis run."""

from dataclasses import dataclass

from matplotlib.figure import Figure
from polars import Boolean, DataFrame, col, concat_str, lit, when

from src.services.comparison import compare_anomaly_methods
from src.services.config import AnalysisConfig
from src.services.dbscan_evidence import evaluate_dbscan_evidence
from src.services.distribution_adequacy import (
    evaluate_distribution_adequacy,
    evaluate_mad_evidence,
)
from src.services.kmeans_evidence import evaluate_kmeans_evidence
from src.services.preprocessing import (
    load_directory,
    load_switching_times_directory,
)
from src.services.statistical_evidence import summarize_statistical_evidence
from src.services.statistics import (
    GaussianFitResult,
    fit_gaussian,
    summarize_statistics,
)
from src.services.validation import (
    ValidationResult,
    load_validation_contract,
    validate_observations,
)
from src.services.visualization import (
    plot_combined,
    plot_dbscan_clusters,
    plot_exceedance_curve,
    plot_kmeans_clusters,
    plot_overvoltage_histogram,
    plot_switching_time_curve,
)


@dataclass(frozen=True, slots=True)
class PipelineFigures:
    """Figures generated by an analysis run."""

    combined: Figure
    exceedance: Figure
    overvoltage_histogram: Figure
    switching_time: Figure
    kmeans_clusters: Figure
    dbscan_clusters: Figure


@dataclass(frozen=True, slots=True)
class PipelineResult:
    """In-memory evidence produced by an analysis run."""

    raw_observations: DataFrame
    validation: ValidationResult
    validated_observations: DataFrame
    annotated_observations: DataFrame
    summary: DataFrame
    statistical_evidence: DataFrame
    distribution_adequacy: DataFrame
    figures: PipelineFigures


def run_pipeline(config: AnalysisConfig) -> PipelineResult:
    """Run loading, validation, analysis, comparison, and plotting.

    Returns:
        Raw and annotated observations, validation evidence, statistical
        summaries, and generated figures.

    Raises:
        ValueError: If the selected observations cannot be analyzed or the
            K-Means cluster count exceeds the analyzed row count.
    """
    raw_observations = load_directory(
        directory=config.input_path,
        base_voltage=config.base_voltage,
        terminal_names=set(config.terminals),
        encoding=config.encoding,
        scenario=config.scenario,
        sample_size=config.sample_size,
        source_lineage=config.source_lineage,
        event_definition=config.event_definition,
    )
    switching_times = load_switching_times_directory(
        directory=config.input_path,
        encoding=config.encoding,
    )
    expected_runs, time_bounds = load_validation_contract(
        config.input_path,
        config.encoding,
    )
    validation = validate_observations(
        raw_observations,
        terminals=config.terminals,
        phases=(config.phase_policy,),
        expected_runs=expected_runs,
        time_bounds=time_bounds,
    )
    if not validation.is_valid:
        message = (
            "The selected observations cannot be analyzed: "
            f"{validation.status.value}."
        )
        raise ValueError(message)

    analyzed = validation.cleaned
    statistical_evidence = summarize_statistical_evidence(
        analyzed,
        threshold=config.threshold,
    )
    distribution_adequacy = evaluate_distribution_adequacy(
        analyzed,
        threshold=config.threshold,
    )
    summary = summarize_statistics(analyzed, threshold=config.threshold)

    with_sigma = _add_sigma_evidence(analyzed, distribution_adequacy)
    with_mad = evaluate_mad_evidence(
        with_sigma,
        threshold=config.mad_threshold,
    )
    with_kmeans = evaluate_kmeans_evidence(
        with_mad,
        n_clusters=config.kmeans.n_clusters,
        random_state=config.kmeans.random_state,
        group_columns=config.grouping_policy,
    )
    with_dbscan = evaluate_dbscan_evidence(
        with_kmeans,
        min_samples=config.dbscan.min_samples,
        effective_eps=config.dbscan.eps,
        group_columns=config.grouping_policy,
    )
    compared = compare_anomaly_methods(with_dbscan)
    fits = _build_plot_fits(analyzed, summary)

    combined, _ = plot_combined(
        compared,
        cluster_col=None,
    )
    exceedance, _ = plot_exceedance_curve(
        df=compared,
        fits=fits,
        cluster_col=None,
    )
    overvoltage_histogram, _ = plot_overvoltage_histogram(compared)
    switching_time, _ = plot_switching_time_curve(switching_times)
    kmeans_clusters, _ = plot_kmeans_clusters(
        compared.filter(col("kmeans_cluster").is_not_null())
    )
    dbscan_clusters, _ = plot_dbscan_clusters(
        compared.filter(col("dbscan_cluster").is_not_null())
    )

    return PipelineResult(
        raw_observations=raw_observations,
        validation=validation,
        validated_observations=analyzed,
        annotated_observations=compared,
        summary=summary,
        statistical_evidence=statistical_evidence,
        distribution_adequacy=distribution_adequacy,
        figures=PipelineFigures(
            combined=combined,
            exceedance=exceedance,
            overvoltage_histogram=overvoltage_histogram,
            switching_time=switching_time,
            kmeans_clusters=kmeans_clusters,
            dbscan_clusters=dbscan_clusters,
        ),
    )


def _add_sigma_evidence(
    observations: DataFrame,
    adequacy: DataFrame,
) -> DataFrame:
    """Append adequacy-qualified three-sigma evidence by full scope."""
    scope = ["scenario", "sample_size", "terminal", "phase"]
    thresholds = adequacy.select(
        *scope,
        (col("fitted_mean") + 3.0 * col("fitted_standard_deviation")).alias(
            "sigma_3_threshold"
        ),
        col("decision").alias("sigma_decision"),
    )
    joined = observations.join(
        thresholds,
        on=scope,
        how="left",
        maintain_order="left",
    ).with_columns(
        when(col("sigma_decision") == "not_rejected")
        .then(lit("applicable"))
        .otherwise(lit("non_applicable"))
        .alias("sigma_applicability")
    )
    return joined.with_columns(
        when(col("sigma_applicability") == "applicable")
        .then(col("value_pu") > col("sigma_3_threshold"))
        .otherwise(lit(None, dtype=Boolean))
        .alias("sigma_flag"),
        when(col("sigma_applicability") == "non_applicable")
        .then(
            concat_str(
                lit("Gaussian adequacy status: "),
                col("sigma_decision"),
                lit("."),
            )
        )
        .when(col("value_pu") > col("sigma_3_threshold"))
        .then(lit("Value exceeds qualified three-sigma threshold."))
        .otherwise(lit(None))
        .alias("sigma_reason"),
    )


def _build_plot_fits(
    observations: DataFrame,
    summary: DataFrame,
) -> dict[str, GaussianFitResult]:
    valid_terminals = set(
        summary.filter(col("validation_status") == "valid")["terminal"]
    )
    fits: dict[str, GaussianFitResult] = {}
    for terminal in valid_terminals:
        subset = observations.filter(col("terminal") == terminal)
        fits[terminal] = fit_gaussian(subset)
    return fits
